#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s steps%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  It tells you what to do, step by step. You can stop with Ctrl-C and run it\n' "$DIM"
  printf '  again whenever you like: nothing already done gets lost.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Step %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────
# Signing a person up for spoochie. Run by whoever is installing, on their machine.
#
# This used to be five steps, with two tokens copied by hand from a Slack screen that
# needs admin access. Too much: the user token was only there to look people up, and
# the bot does that. Now whoever signs you up sends you one line and this pastes it.

TOTAL_STAGES=4
SPOOCHIE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
sp() { bun run "$SPOOCHIE/src/cli.ts" "$@"; }

banner "spoochie — sign up"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Requirements"
say "spoochie needs Bun and a Claude Code version with a session inbox."
missing=0
if command -v bun >/dev/null 2>&1; then step "bun $(bun --version)"; else step "MISSING bun — https://bun.sh"; missing=1; fi
if command -v claude >/dev/null 2>&1; then step "claude $(claude --version 2>/dev/null | head -1)"; else step "MISSING claude"; missing=1; fi
if [ -n "${CLAUDE_CODE_MESSAGING_SOCKET:-}" ]; then
  step "this session's inbox: $CLAUDE_CODE_MESSAGING_SOCKET"
else
  step "this session has no inbox; the hook fixes that when Claude Code restarts"
fi
[ "$missing" = 1 ] && { say ""; say "Install what is missing and run this again."; exit 1; }
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Paste the invitation"
say "Whoever signs you up ran 'spoochie invite' and sent you a line that starts"
say "with 'spoochie join'. Paste it here in full, with its --user if it has one."
say ""
say "You don't need to install anything in Slack or have any token of your own:"
say "the invitation carries the bot's, which belongs to the app and not to anyone."
say ""
ask LINE "Paste the full line:"
LINE="${LINE#spoochie }"
case "$LINE" in
  join\ *) : ;;
  *) say ""; say "That doesn't look like an invitation. It has to start with 'spoochie join'."; exit 1 ;;
esac
# shellcheck disable=SC2086
sp $LINE || { say ""; say "It didn't go through. Ask for a new invitation and try again."; exit 1; }
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Hook it into your Claude sessions"
say "spoochie registers itself when a session starts, with a hook. With the plugin"
say "there is no file to edit by hand."
say ""
step "In Claude Code:  /plugin marketplace add edugargar/spoochie"
step "Then:            /plugin install spoochie@edugargar"
say ""
say "If you'd rather not use the marketplace, add this to your ~/.claude/settings.json:"
say "  \"SessionStart\": [{\"hooks\":[{\"type\":\"command\",\"command\":\"bun run $SPOOCHIE/src/cli.ts register\"}]}]"
say "  \"SessionEnd\":   [{\"hooks\":[{\"type\":\"command\",\"command\":\"bun run $SPOOCHIE/src/cli.ts unregister\"}]}]"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Check that it really delivers"
say "Two checks. The first one doesn't touch Slack or need anyone."
say ""
sp selftest || true
say ""
sp doctor || true
say ""
say "When someone opens a spoochie with you, the bot sends you a DM. Reply in the thread"
say "to accept it, or tell your Claude:  spoochie accept <id>"
say ""
say "And you don't have to learn any commands to use it: tell your Claude in plain words"
say "'open a spoochie with Edu about the modal save error'."
