#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s pasos%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  Te va diciendo que hacer paso a paso. Puedes cortar con Ctrl-C y volver\n' "$DIM"
  printf '  a lanzarlo cuando quieras: no se pierde nada de lo que ya este hecho.%s\n' "$RESET"
  pause "¿Empezamos?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Paso %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Pulsa Enter para seguir}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# ──────────────────────────────────────────────────────────────────────────

# ──────────────────────────────────────────────────────────────────────────
# Alta de una persona en spoochie. Lo corre quien se instala, en su maquina.
#
# Antes esto eran cinco pasos, con dos tokens copiados a mano de una pantalla de
# Slack a la que hace falta acceso de admin. Sobraba: el token de usuario solo
# servia para buscar personas, y eso lo hace el bot. Ahora quien te da de alta te
# manda una linea y esto la pega.

TOTAL_STAGES=4
SPOOCHIE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
sp() { bun run "$SPOOCHIE/src/cli.ts" "$@"; }

banner "spoochie — darte de alta"

# ── 1 ─────────────────────────────────────────────────────────────────────
stage "Requisitos"
say "spoochie necesita Bun y una version de Claude Code con buzon de sesion."
falta=0
if command -v bun >/dev/null 2>&1; then step "bun $(bun --version)"; else step "FALTA bun — https://bun.sh"; falta=1; fi
if command -v claude >/dev/null 2>&1; then step "claude $(claude --version 2>/dev/null | head -1)"; else step "FALTA claude"; falta=1; fi
if [ -n "${CLAUDE_CODE_MESSAGING_SOCKET:-}" ]; then
  step "buzon de esta sesion: $CLAUDE_CODE_MESSAGING_SOCKET"
else
  step "esta sesion no tiene buzon; el hook lo arregla al reiniciar Claude Code"
fi
[ "$falta" = 1 ] && { say ""; say "Instala lo que falta y vuelve a lanzarlo."; exit 1; }
pause

# ── 2 ─────────────────────────────────────────────────────────────────────
stage "Pegar la invitacion"
say "Quien te da de alta ha corrido 'spoochie invite' y te ha pasado una linea que"
say "empieza por 'spoochie join'. Pegala entera aqui, con su --email o su --user."
say ""
say "No hace falta que instales nada en Slack ni que tengas ningun token tuyo:"
say "la invitacion trae el del bot, que es de la app y no de nadie."
say ""
ask LINEA "Pega la linea completa:"
LINEA="${LINEA#spoochie }"
case "$LINEA" in
  join\ *) : ;;
  *) say ""; say "Eso no parece una invitacion. Tiene que empezar por 'spoochie join'."; exit 1 ;;
esac
# shellcheck disable=SC2086
sp $LINEA || { say ""; say "No ha entrado. Pide una invitacion nueva y vuelve a intentarlo."; exit 1; }
pause

# ── 3 ─────────────────────────────────────────────────────────────────────
stage "Engancharlo a tus sesiones de Claude"
say "spoochie se registra solo al arrancar una sesion, con un hook. Con el plugin"
say "no hay que tocar ningun fichero a mano."
say ""
step "En Claude Code:  /plugin marketplace add edugargar/spoochie"
step "Y despues:       /plugin install spoochie@edugargar"
say ""
say "Si prefieres no usar el marketplace, anade a tu ~/.claude/settings.json:"
say "  \"SessionStart\": [{\"hooks\":[{\"type\":\"command\",\"command\":\"bun run $SPOOCHIE/src/cli.ts register\"}]}]"
say "  \"SessionEnd\":   [{\"hooks\":[{\"type\":\"command\",\"command\":\"bun run $SPOOCHIE/src/cli.ts unregister\"}]}]"
pause

# ── 4 ─────────────────────────────────────────────────────────────────────
stage "Comprobar que entrega de verdad"
say "Dos comprobaciones. La primera no toca Slack ni necesita a nadie."
say ""
sp selftest || true
say ""
sp doctor || true
say ""
say "Cuando alguien te abra un spoochie te llegara un DM del bot. Contesta en el hilo"
say "para aceptarlo, o dile a tu Claude:  spoochie accept <id>"
say ""
say "Y para usarlo no tienes que aprenderte comandos: dile a tu Claude en cristiano"
say "'abre un spoochie con Edu sobre el error de guardado del modal'."
